### ISSUE TITLE
Problems about running the code

### ISSUE THREAD

**Issue by d12306** [haldai/LASIN#2]
Hi, @haldai , thanks for your implementation. I have a question: can you show some command lines in order to run the experiments. I am actually not adept in using Swi-proplog. Thanks,

**Comment by haldai** [comment]
> Hi, @haldai , thanks for your implementation. I have a question: can you show some command lines in order to run the experiments. I am actually not adept in using Swi-proplog. Thanks,

Hi, I have added some instructions in the `README` file for running the codes. But I am sorry that the codes are still being cleaning and tidying, more detailed instructions will be added later.
